# Generated by Django 4.2.2 on 2023-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=512)),
                ('notes', models.CharField(default='', max_length=512)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
    ]
