# Generated by Django 4.2.2 on 2023-06-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0003_satus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Satus',
            new_name='Status',
        ),
    ]
