# Generated by Django 4.2.2 on 2023-06-28 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0004_rename_satus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams_app.status'),
            preserve_default=False,
        ),
    ]
