# Generated by Django 4.2.6 on 2024-05-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
