# Generated by Django 4.2.6 on 2024-05-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0007_relationship_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
