# Generated by Django 4.2.6 on 2024-06-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='origin_application',
            field=models.CharField(default='Unknown', max_length=128),
        ),
    ]
