# Generated by Django 4.2.6 on 2025-06-02 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teams_app', '0009_team_origin_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username_hash', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
    ]
