# Generated by Django 4.2.6 on 2025-06-05 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0010_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_role', to='teams_app.role'),
        ),
    ]
